version: '3'
services:

  wordpress:
    image: wordpress
    ports:
      - 8080:80
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_PASSWORD: abc123456
    networks:
      - my-bridge

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: abc123456
      MYSQL_DATABASE: wordpress
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - my-bridge

volumes:
  mysql:

networks:
  my-bridge:
    driver: bridge